const mockProductDetails = {
  product_id: 'classic-canvas-tee',
  name: 'Classic Canvas Tee',
  description:
    'The Classic Canvas Tee is your go-to wardrobe staple, offering unparalleled comfort and a timeless look that never goes out of style.',
  category: 'unisex',
  collection: 'fresh',
  created_at: '2024-02-26',
  sizing_convention: 'clothes',
  available_colors: ['beige', 'brown', 'orange', 'red', 'white'],
  inventory: [
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-white-xs',
      color: 'white',
      size: 'xs',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 100,
      stock: 900,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-white-sm',
      color: 'white',
      size: 'sm',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 90,
      stock: 910,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-white-md',
      color: 'white',
      size: 'md',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 80,
      stock: 920,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-white-lg',
      color: 'white',
      size: 'lg',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 70,
      stock: 930,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-white-xl',
      color: 'white',
      size: 'xl',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 60,
      stock: 940,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-red-xs',
      color: 'red',
      size: 'xs',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 100,
      stock: 900,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-red-sm',
      color: 'red',
      size: 'sm',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 90,
      stock: 910,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-red-md',
      color: 'red',
      size: 'md',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 80,
      stock: 0,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-red-lg',
      color: 'red',
      size: 'lg',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 70,
      stock: 930,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-red-xl',
      color: 'red',
      size: 'xl',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 60,
      stock: 940,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-orange-xs',
      color: 'orange',
      size: 'xs',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 100,
      stock: 900,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-orange-sm',
      color: 'orange',
      size: 'sm',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 90,
      stock: 910,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-orange-md',
      color: 'orange',
      size: 'md',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 80,
      stock: 920,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-orange-lg',
      color: 'orange',
      size: 'lg',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 70,
      stock: 930,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-orange-xl',
      color: 'orange',
      size: 'xl',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 60,
      stock: 940,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-brown-xs',
      color: 'brown',
      size: 'xs',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 100,
      stock: 900,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-brown-sm',
      color: 'brown',
      size: 'sm',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 90,
      stock: 910,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-brown-md',
      color: 'brown',
      size: 'md',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 80,
      stock: 920,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-brown-lg',
      color: 'brown',
      size: 'lg',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 70,
      stock: 930,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-brown-xl',
      color: 'brown',
      size: 'xl',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 60,
      stock: 940,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-beige-xs',
      color: 'beige',
      size: 'xs',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 100,
      stock: 0,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-beige-sm',
      color: 'beige',
      size: 'sm',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 90,
      stock: 0,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-beige-md',
      color: 'beige',
      size: 'md',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 80,
      stock: 0,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-beige-lg',
      color: 'beige',
      size: 'lg',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 70,
      stock: 0,
    },
    {
      product_id: 'classic-canvas-tee',
      sku: 'cct-beige-xl',
      color: 'beige',
      size: 'xl',
      list_price: 25,
      discount: null,
      discount_percentage: 10,
      sale_price: 22.5,
      sold: 60,
      stock: 0,
    },
  ],
};

export default mockProductDetails;
